spring:
  data:
    mongodb:
      uri: "mongodb://root:example@localhost:27017/tacocloudb?authSource=admin"
      # host: localhost
      # port: 27017
      # username: root
      # password: example
      # database: tacoclouddb

